apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo
  labels:
    app: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: threepapertrail/todo-api:7da579adc612866e2069
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: todo-api-config
