grafana:
  adminPassword: admin
  ingress:
    enabled: false
  service:
    type: ClusterIP
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-stack.observability.svc.cluster.local:3100
      access: proxy
prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    storageSpec:
      emptyDir: {}
