grafana:
  adminPassword: admin
  ingress:
    enabled: false
  service:
    type: ClusterIP
  image:
    tag: 11.5.2
prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    storageSpec:
      emptyDir: {}
