# Install ArgoCD v3.4.5
# kubectl create namespace argocd
# kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.5/manifests/install.yaml

# Patch argocd-server to LoadBalancer
# kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

# Disable HTTPS (homelab, no need for TLS)
# kubectl patch configmap argocd-cmd-params-cm -n argocd --type merge -p '{"data":{"server.insecure":"true"}}'
# kubectl rollout restart deployment argocd-server -n argocd
