apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: todo
  labels:
    app: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
        - name: locust
          image: locustio/locust:2.46.2
          args:
            - "-f"
            - "/mnt/locust/locustfile.py"
            - "--host"
            - "http://todo-api.todo.svc.cluster.local:80"
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: locustfile
              mountPath: /mnt/locust
      volumes:
        - name: locustfile
          configMap:
            name: locustfile
