apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: todo
  labels:
    app: locust
spec:
  type: LoadBalancer
  selector:
    app: locust
  ports:
    - name: web
      port: 8089
      targetPort: 8089
